#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
	
if [[$(xrandr -q | grep 'HDMI-A-0 connected')]]; 
then
xrandr --output eDP --primary --mode 1920x1080 --rotate normal 
--output HDMI-A-0 --mode 1920x1080 --rotate normal
bspc eDP -d I II III IV V
bspc HDMI-A-0 -d VI VII VIII IX X
else 
bspc monitor -d I II III IV V VI VII VIII IX X 
fi

bspc monitor -g 1920x1080+0+0

bspc config border_width        1
bspc config window_gap          9

bspc config split_ratio          0.58
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true


bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a VSCodium desktop='^3'
bspc rule -a Qt Creator desktop='^4'
bspc rule -a intellij-diea-community-editon deskop='5'
bspc rule -a pycharm-community-editoion='6'
bspc rule -a lmms desktop='^7'
bspc rule -a Lutris desktop='^8'

# Border
bspc config normal_border_color "#44475a"
bspc config active_border_color "#FFC0CB"
bspc config focused_border_color "#ff10f0"
bspc config presel_feedback_color "#6272a4"


#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 74.97 &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

